version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=167916
      - POSTGRES_DB=roomate
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # environment:
    #   - DB_SOURCE=postgresql://root:167916@postgres:5432/roomate?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
